export const actionTypes = {
  
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  FETCH_INGREDIENTS_START: 'FETCH_INGREDIENTS_START',
  FETCH_INGREDIENTS_SUCCESS: 'FETCH_INGREDIENTS_SUCCESS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',

  PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
  PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
  PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
  PURCHASE_INIT: 'PURCHASE_INIT',

  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL'
}